import { RotateCcw, Download, LayoutDashboard } from "lucide-react";
import { useNavigate } from "react-router-dom";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function ActionButtons({ interviewData, candidateData }) {

  const navigate = useNavigate();

  const handleRetake = () => {
    navigate("/hr");
  };

  const handleDashboard = () => {
    navigate("/student/dashboard");
  };

  const handleDownload = () => {

    const doc = new jsPDF();

    // ===== HEADER =====
    doc.setFontSize(20);
    doc.text("AI Interview Performance Report", 14, 20);

    doc.setFontSize(11);
    doc.setTextColor(100);

    doc.text(
      "AI-driven evaluation of communication, confidence, and answer relevance.",
      14,
      28
    );

    // ===== CANDIDATE INFO =====
    doc.setTextColor(0);
    doc.setFontSize(13);

    doc.text("Candidate Information", 14, 40);

    doc.setFontSize(11);

    doc.text(`Name: ${candidateData?.name}`, 14, 48);
    doc.text(`Interview Type: ${candidateData?.type}`, 14, 55);
    doc.text(`Date: ${candidateData?.date}`, 14, 62);

    // ===== SCORE TABLE =====
    autoTable(doc, {
      startY: 75,
      head: [["Performance Metric", "Score"]],
      body: [
        ["Final Interview Score", interviewData?.finalScore],
        ["Content Relevance Score", interviewData?.contentScore],
        ["Voice Confidence Score", interviewData?.voiceConfidence]
      ],
      theme: "grid",
      headStyles: { fillColor: [41, 128, 185] }
    });

    // ===== QUESTION FEEDBACK TABLE =====
    const feedbackRows = interviewData?.answers?.map((a) => [
      a.question,
      a.transcript || "Speech Answer",
      a.scores?.final_confidence || "N/A",
      a.improvements || "-"
    ]) || [];

    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 10,
      head: [["Question", "Answer Summary", "Score", "Feedback"]],
      body: feedbackRows,
      styles: { fontSize: 9 },
      theme: "striped",
      headStyles: { fillColor: [52, 73, 94] }
    });

    // ===== COLLECT UNIQUE STRENGTHS =====
    const strengths = [
      ...new Set(
        interviewData?.answers
          ?.map((a) => a.strengths)
          .filter(Boolean)
      )
    ];

    // ===== COLLECT UNIQUE IMPROVEMENTS =====
    const improvements = [
      ...new Set(
        interviewData?.answers
          ?.map((a) => a.improvements)
          .filter(Boolean)
      )
    ];

    let y = doc.lastAutoTable.finalY + 15;

    // ===== STRENGTHS =====
    doc.setFontSize(14);
    doc.text("Key Strengths", 14, y);

    y += 8;

    doc.setFontSize(11);

    strengths.forEach((s) => {

      const lines = doc.splitTextToSize(`• ${s}`, 180);

      doc.text(lines, 18, y);

      y += lines.length * 6;

    });

    // ===== IMPROVEMENTS =====
    y += 6;

    doc.setFontSize(14);
    doc.text("Areas for Improvement", 14, y);

    y += 8;

    doc.setFontSize(11);

    improvements.forEach((imp) => {

      const lines = doc.splitTextToSize(`• ${imp}`, 180);

      doc.text(lines, 18, y);

      y += lines.length * 6;

    });

    // ===== AI RECOMMENDATION =====
    if (interviewData?.aiRecommendation) {

      y += 10;

      doc.setFontSize(14);
      doc.text("AI Recommendation", 14, y);

      y += 8;

      doc.setFontSize(11);

      const lines = doc.splitTextToSize(
        interviewData.aiRecommendation,
        180
      );

      doc.text(lines, 18, y);

    }

    // ===== FOOTER =====
    doc.setFontSize(9);
    doc.setTextColor(120);

    doc.text(
      "Generated by AI Interview Preparation System",
      14,
      285
    );

    doc.save("AI_Interview_Report.pdf");

  };

  return (
    <div className="flex flex-wrap gap-4 justify-center">

      <button
        onClick={handleRetake}
        className="bg-blue-600 text-white px-6 py-3 rounded-lg flex items-center gap-2"
      >
        <RotateCcw size={18} />
        Retake Interview
      </button>

      <button
        onClick={handleDownload}
        className="border border-blue-600 text-blue-600 px-6 py-3 rounded-lg flex items-center gap-2"
      >
        <Download size={18} />
        Download Report
      </button>

      <button
        onClick={handleDashboard}
        className="border border-gray-300 text-gray-700 px-6 py-3 rounded-lg flex items-center gap-2"
      >
        <LayoutDashboard size={18} />
        Go to Dashboard
      </button>

    </div>
  );
}

export default ActionButtons;